### ISSUE TITLE
Server Issue.

### ISSUE THREAD

**Issue by codemeister101** [Team-RAM/RAM#27]
I set up a server with  RAM-0.2.6_server_FULL and it works perfectly fine and I am able to connect to it with no problem but when you go to join it always states Incompatible FML server but anyone is still able to connect to it anyways. Is there a fix for this? 

![Annotation 2020-03-07 185023](https://user-images.githubusercontent.com/23063822/76154636-69da3580-60a5-11ea-82a9-3283d0af5ad0.png)

**Comment by Yamza** [comment]
No, this is not possible to fix currently. It's checking that client and server mods match, but client mods don't all work on the server.
