### ISSUE TITLE
Crash while playing

### ISSUE THREAD

**Issue by Wratox** [Team-RAM/RAM#28]
Was trying out this modpack but it started to crash after not much playing. Sometimes it crashes a few seconds into the game, other times i can play for a few minutes or even for a longer period of time before it crashes.

Not sure if the crashes are caused by this pack or a single mod. So far all the crashes have given the following crash message:
`The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=stage, clazz=class java.lang.Integer, values=[0, 1]} as it does not exist in Block{minecraft:void_air}`

[Crash-log](http://s.yoosk.pl/EuGAR)

Just ask if there's anything else is needed.

**Comment by Darkere** [comment]
Reported to the dev. Natures aura is trying to render particles for a non-existant bamboo block.

**Comment by Darkere** [comment]
@Wratox Any chance you can provide a world download? Dev is hiding behind the fact that other mods may be interfering with what he is doing.

**Comment by Wratox** [comment]
[Uploaded here](https://easyupload.io/r0mof8), file only lasts for 30 days

**Comment by Darkere** [comment]
Dev has fixed the issue. Unfortunately, that fix will not make into today's update but it most likely will into the next.

The issue is caused by bamboo being grown at the top of the world. You should be able to move away from the amplified bamboo forest and be fine.

**Comment by Wratox** [comment]
Okay thanks! 

Then I atleast know what to avoid until that fix, also thanks for the fast responses 👍
