### ISSUE TITLE
Server connection problem

### ISSUE THREAD

**Issue by Geslerrr** [Team-RAM/RAM#35]
So i installed Ram server full version 0.2.7. and i have the same client version. It is working but i cant connect to it and these two messages pops up allways when i try. Had I done anything wrong or is this real issue?
![Zrzut ekranu (5)](https://user-images.githubusercontent.com/16934194/77233353-41733080-6ba7-11ea-9f67-cb440532d280.png)
![Zrzut ekranu (4)](https://user-images.githubusercontent.com/16934194/77233362-4a640200-6ba7-11ea-8a58-391bb38a0933.png)

**Comment by Darkere** [comment]
The top error will unfortunately always be there for now. Ignore it.

Post your latest.log and we can take a look at what's up.

**Comment by Geslerrr** [comment]
[latest.log](https://github.com/Team-RAM/RAM/files/4363631/latest.log)

**Comment by Darkere** [comment]
That looks like you either have different versions or a broken download somewhere. please try reinstalling

**Comment by Geslerrr** [comment]
ok, reinstalling helped me but while i was joining world a loads of errors appeared, so i will attach this here. thanks a lot 
[serverlog.txt](https://github.com/Team-RAM/RAM/files/4364173/serverlog.txt)

**Comment by Darkere** [comment]
great.
No problematic errors there.
