### ISSUE TITLE
crashes when a mob dies on the dark utils player trap 

### ISSUE THREAD

**Issue by Seegras** [Team-RAM/RAM#41]
It reports a block being collided with an entity

-- Block being collided with --
Details:
        Block: Block{darkutils:rune_damage_player}[powered=false,waterlogged=false]
Stacktrace:
        at net.minecraft.entity.Entity.func_145775_I(Entity.java:815)

-- Entity being checked for collision --
Details:
        Entity Type: minecraft:zombie(net.minecraft.entity.monster.ZombieEntity)

**Comment by Yoosk** [comment]
FTB quests doing that https://github.com/FTBTeam/FTB-Quests/issues/390, we have to wait for mod to update.
