### ISSUE TITLE
Modpack crashes on launch

### ISSUE THREAD

**Issue by Bloodfang282** [Team-RAM/RAM#43]
I just downloaded the RAM modpack today(4-5-20) with some friends, and they launched their pack just fine and got into the world, but when I launched the pack, the game crashes before it even starts to load the pack. The notice it gives me afterward only says it had an issue, but it doesn't say what the issue was. Someone, please help I would like to play the pack.

**Comment by Bloodfang282** [comment]
This is the notice.
![Minecraft crash Capture](https://user-images.githubusercontent.com/63211987/78511231-a068a600-7760-11ea-848a-eaecff1ff85e.JPG)

**Comment by Yamza** [comment]
Assuming you are using Twitch, you will need to select another pack launcher. 

- ATLauncher: https://atlauncher.com/downloads Fairly simple setup. Drag the file to your preferred install location and run it. You can then add the pack by selecting Packs and then Add Curse Pack, then input the curseforge url below.

- GDLauncher: https://github.com/CrankySupertoon/GDLauncher-arch/releases/tag/v0.12.5 Simply use the pack browser and search for RAM.

- MultiMC
