### ISSUE TITLE
NullPointerException on quests button

### ISSUE THREAD

**Issue by badalya1** [Team-RAM/RAM#47]
When opening inventory there is a button on top left corner that says "Quests". Clicking it causes the game to exit with NullPointerException.

"The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler" 

[crash-2020-04-18_17.34.27-client.txt](https://github.com/Team-RAM/RAM/files/4497816/crash-2020-04-18_17.34.27-client.txt)

**Comment by Darkere** [comment]
That looks like you may be missing some files in your install?

**Comment by badalya1** [comment]
@Darkere  indeed, the server was not configured properly.
