### ISSUE TITLE
Update to latest prelaunch scrips for multimc

### ISSUE THREAD

**Issue by sargunv** [Team-RAM/RAM#48]
You need to grab the latest PlatformLauncher and modsman-packutil.sh files from https://github.com/sargunv-mc-mods/modsman-modpack-example. There was a bad commit up on master for a couple hours and it seems like you got that version. Without this fix, it's broken on macOS and Linux.

**Comment by Yoosk** [comment]
It was only a test if curse will accept the files, all good and now its hidden.
