### ISSUE TITLE
fore not recognizing zip files?

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [Team-RAM/RAM#49]
i tried putting it in the mods folder but it didnt recognize any mod but forge and minecraft itself. tried renaming it to a jar file and it said its an invalid jar file? help please?

**Comment by Darkere** [comment]
The Zip file contains a list of mods to download not the mods themselves. You will need to use a launcher that downloads and installs the mods for you. 

Most popular and official launcher would be [Twitch ](https://www.twitch.tv/downloads)

**Comment by tails1974seeyounextgame** [comment]
i installed twitch and ran the twitch button to try downloading a single mod on the website file but twitch for pc literally did nothing. it just stared at me.

**Comment by Darkere** [comment]
In the twitch app go to Mods ⇾ Minecraft ⇾ Browse Modpacks ⇾ search for RAM and press install. 
To start then go to my modpacks.
