### ISSUE TITLE
[3.3.1] Mystical Agriculture watering can can't be used directly on crops

### ISSUE THREAD

**Issue by MegaHakkero** [Team-RAM/RAM#53]
Some unknown mod in this pack seems to inhibit the right-click function on crops completely, thus making you unable to use the Mystical Agriculture watering can directly on crops, making it impossible to water big fields of them.
I tried disabling Harvestcraft's "harvest on right click" feature, as well as Quark's "Simple harvest", neither of which helped.

Modpack version: 3.3.1

**Comment by Darkere** [comment]
Weird. Not sure if that is mystical agriculture itself or something else. 

Anyway by shift right clicking with the watering can you can make it always active. Which allows you to use it just fine while aiming at a crop.

**Comment by mixednutts** [comment]
I saw this behaviour and found it was Pam's harvest config had harvest on RMC enabled and overrides the watering can function.

**Comment by MegaHakkero** [comment]
Oh, I didn't know about that trick, Dark. Also, just in case, @mixednutts which setting is it? I tried setting
```
"Enable right-click harvesting for crops" = false
```
on both lines it appears in both pamhc2crops.toml and pamhc2trees.toml without any effect, at least not after a /reload.

**Comment by Darkere** [comment]
A /reload should not affect that. A restart would be required.

**Comment by MegaHakkero** [comment]
Ouch. Alright, issue closed then. ^-^
