### ISSUE TITLE
Can't open .bat

### ISSUE THREAD

**Issue by Jupinzonl** [Team-RAM/RAM#55]
Hey!

I got a problem installing a server with your modpack, when I try yo open the .bat file it just shows this error,

 

INFO: Checking java installation...

ERROR: Could not find 64-bit Java 1.8 installed or in PATH
Press any key to continue . . .

 

 

Yet i tried everything, I changed the path to recognize java, uninstalled and reinstalled 5 times, moving java to another folder, yet i can't find a solution. Can you help me find an answer to this.

 

Thanks in advance

**Comment by FallenEagle1** [comment]
Did you double check that your java is 64 bit and not 32 bit?

**Comment by Jupinzonl** [comment]
I just opened it after a restart and it worked, supposed windows confussions are real
