### ISSUE TITLE
[GoodNightSleep] Negatite Ore is unfindable.

### ISSUE THREAD

**Issue by Ruchian** [Team-RAM/RAM#65]
You for some reason made negatite ore, which should have the same rarity as diamond four to eight times more difficult to find than netherrite in 1.16
I fear this bug occured because there is too much Silent Gems going on everywhere. It spawns like nuts.

Please fix the ores. I can't make a stupid bed to the nightmare dimension due to this.

Negatite ore spawns between y level 5 and y level 15 in the Nightmare dimension.
It's a resource that should be pretty common (somewhat more than diamond). 
![2020-07-02_02 42 05](https://user-images.githubusercontent.com/24900404/86304252-a6aad900-bc0e-11ea-9c44-80483e9e1320.png)

Tell me if you see any.... and try to find it in Survival mode. Good luck.......
edit: @KingPhygieBoo > https://gitlab.com/KingPhygieBoo 
I wonder what he would say if he saw this.

**Comment by KingPhygieBoo** [comment]
There's going to be a Good Night's Sleep update coming out soon that should iron out both the bed issue, and the ore issues, as well as the dimensions being filled with other mod's ores.

**Comment by Ruchian** [comment]
Cool, thanks for the reply. Sorry for the ping. I was just curious if it was normal for it to be so rediculously rare. xD

**Comment by KingPhygieBoo** [comment]
All issues have been addressed in the latest v1.1.0 release, sorry for any inconvenience

**Comment by Ruchian** [comment]
By the way, a phantom just randomly spawned while I was exploring the nightmare dimension on a server. Is that normal?
Note that, with the pack defaults which the server runs on, time is frozen in that dim on midnight.

**Comment by KingPhygieBoo** [comment]
That is intentional, however it can be disabled as of the latest update.

**Comment by Ruchian** [comment]
Cool. You work fast omg. My compliments. Though it wasn't a feature request, just checking in on it since you were reading, but I can see indeed why some may want it disabled since according to the mod lore, they're sleeping. Hm, phantoms are a good thing with nightmares, though I guess if they would always spawn randomly instead of after having not slept because the overworld time passed, that it would make more sense in there. At least thanks for answering the questions. ;p

I'll close the topic once Team RAM updated their modpack to include your updated release.

**Comment by KingPhygieBoo** [comment]
No problem, if you have any other issues with the mod please let me know

**Comment by Ruchian** [comment]
I have the feeling that pack updates will not be coming. It's half a year later and its still 0.4.4 and having the older version.
In response and since the bug is fixed anyway in a future version of the mod, I am closing this.
